//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3623 版自动生成。
// 
namespace HandheldTerminal_Supervision.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IDBInterface", Namespace="http://tempuri.org/")]
    public partial class DBInterfaceRealization : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DBInterfaceRealization() {
            this.Url = "http://127.0.0.1:9527/";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDBInterface/GetDataTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetDataTable([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RequestCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.DataSet parameterDic) {
            object[] results = this.Invoke("GetDataTable", new object[] {
                        user,
                        RequestCode,
                        parameterDic});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataTable(string user, string RequestCode, System.Data.DataSet parameterDic, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataTable", new object[] {
                        user,
                        RequestCode,
                        parameterDic}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetDataTable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
